services:
  reportable_service_db:
    image: postgres:17-bookworm
    container_name: reportable_service_db
    environment:
      POSTGRES_USER: '${REPORTABLE_DB_USER}'
      POSTGRES_PASSWORD: '${REPORTABLE_DB_PASSWORD}'
      POSTGRES_DB: '${REPORTABLE_DB_NAME}'
    ports:
      - '${REPORTABLE_DB_PORT}:5432'
    expose:
      - 5432
    volumes:
      - reportable_service_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${REPORTABLE_DB_USER} -d ${REPORTABLE_DB_NAME}"]
      interval: 10s
      timeout: 2s
      retries: 10

  minio:
    image: minio/minio:latest
    ports:
      - "9003:9000"
      - "9004:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9004" /data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    expose:
      - 6379
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]

volumes:
  reportable_service_data:
  minio_data:
  redis_data: